// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLEbWH9YpFtLyxB718HMsKdQA7UMLqJPU',
    appId: '1:30302854209:web:fe56ab5c69ba81f8d4fac0',
    messagingSenderId: '30302854209',
    projectId: 'krishnamay-6602b',
    authDomain: 'krishnamay-6602b.firebaseapp.com',
    storageBucket: 'krishnamay-6602b.appspot.com',
    measurementId: 'G-M50DWCF230',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBZUyzciBMx1spssronfz5A6LUX5V930',
    appId: '1:30302854209:android:b61a396008c3f85cd4fac0',
    messagingSenderId: '30302854209',
    projectId: 'krishnamay-6602b',
    storageBucket: 'krishnamay-6602b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIkUaxTFS0PyBC6ZsYy8TsYkpqVbJqDk',
    appId: '1:30302854209:ios:2f689fc52bbd2abad4fac0',
    messagingSenderId: '30302854209',
    projectId: 'krishnamay-6602b',
    storageBucket: 'krishnamay-6602b.appspot.com',
    iosBundleId: 'com.example.krishnamay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvIkUaxTFS0PyBC6ZsYy8TsYkpqVbJqDk',
    appId: '1:30302854209:ios:4ff077001e83430dd4fac0',
    messagingSenderId: '30302854209',
    projectId: 'krishnamay-6602b',
    storageBucket: 'krishnamay-6602b.appspot.com',
    iosBundleId: 'com.example.krishnamay.RunnerTests',
  );
}
